MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using System.Net;
using System.Net.Mime;

namespace MVC.Controllers
{
    //[Authorize]
    public class CustomerController : Controller
    {
        NorthwindEntities context = new NorthwindEntities();
        // GET: Customer
        public ActionResult GetAllCustomers()
        {
            var cust = context.Customers.ToList();
            var customers = new CustomerList()
            {
                allCustomers = cust
            };
            //return View(customers);

            return View();
        }

        //public ActionResult GetParticularCustomer(string id)
        //{
        //    var cust = context.Customers.ToList();
        //    var particularCustomer = cust.Find(c => c.CustomerID == id);
        //    return View(particularCustomer);
        //}

        public ActionResult GetParticularCustomer(string id)
        {
            var cust = context.Customers.ToList();
            var particularCustomer = cust.Find(c => c.CustomerID == id);
            return View("GetAllCustomers", particularCustomer);
        }

        public ActionResult AddNew()
        {
            ViewBag.Action = 1;
            return View("GetAllCustomers");
        }

        public ActionResult SaveCustomer(Customer customer)
        {
            using (var contextTransaction = context.Database.BeginTransaction())
            {
                try
                {
                    context.SaveChanges();
                    contextTransaction.Commit();
                }
                catch (Exception)
                {
                    contextTransaction.Rollback();
                }
            }
                return View("GetAllCustomers");
        }

        public ActionResult ContactDetails(List<Customer> cust)
        {
            var x = cust;
            var z = x;

            return Json(new { success = true, responseText = "Your message successfuly sent!" });
        }
    }
}

MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using MVC.ViewModel;
using MVC.Custom;

namespace MVC.Controllers
{
    //[Authorize]
    public class ProductController : Controller
    {
        NorthwindEntities context = new NorthwindEntities();
        // GET: Product
        [MyAuthorize(Role = "Administrator")]
        public ActionResult GetAllProducts()
        {
            var products = context.Products.ToList();
            var allProducts = new ProductList()
            {
                allProducts = products
            };

            return View(allProducts);
        }

        public ActionResult GetParticularProduct(int? id)
        {
            var allProducts = context.Products.ToList();
            var particularProduct = allProducts.Find(p => p.ProductID == id);

            if (!id.HasValue)
            {
                return HttpNotFound();
            }
            else if (particularProduct == null)
            {
                return HttpNotFound();
            }

            var productDetails = new ProductCategories()
            {
                Product = particularProduct,
                Categories = context.Categories.ToList(),
                Suppliers = context.Suppliers.ToList()
            };

            ViewBag.Header = "Edit Product";
            return View("ProductForm", productDetails);
        }

        public ActionResult ProductForm()
        {
            var cat = context.Categories.ToList();
            var sup = context.Suppliers.ToList();
            var prodCategories = new ProductCategories()
            {
                Categories = cat,
                Suppliers = sup
            };

            ViewBag.Header = "Add New Product";
            return View(prodCategories);
        }

        [HttpPost]
        public ActionResult SaveProduct(ProductCategories prodCategories)
        {
            if (!ModelState.IsValid)
            {
                return View("ProductForm", prodCategories);
            }

            if (prodCategories.Product.ProductID == 0)
            {
                context.Products.Add(prodCategories.Product);
            }
            else
            {
                var productFromDB = context.Products.Single(p => p.ProductID == prodCategories.Product.ProductID);
                productFromDB.ProductName = prodCategories.Product.ProductName;
                productFromDB.SupplierID = prodCategories.Product.SupplierID;
                productFromDB.UnitPrice = prodCategories.Product.UnitPrice;
                productFromDB.CategoryID = prodCategories.Product.CategoryID;
                productFromDB.UnitsInStock = prodCategories.Product.UnitsInStock;
            }

            context.SaveChanges();

            return RedirectToAction("GetAllProducts");
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WalShop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">     
                    <li>@Html.ActionLink("Products", "GetAllProducts", "Product")</li>
                    <li>@Html.ActionLink("Category", "GetAllCategories", "Category")</li>
                    <li>@Html.ActionLink("Customers", "GetAllCustomers", "Customer")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WalShop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>